# kubectl create secret generic app-secret --from-literal=DB_HOST=mysql --from-literal=DB_USER=root --from-literal=DB_PASSWORD=paswrd
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  # only encoded, not encrypted
  DB_HOST: # echo -n 'mysql' | base64 <-> echo -n 'mysql' | base64 --decode
  DB_USER: # echo -n 'root' | base64 <-> echo -n 'root' | base64 --decode
  DB_PASSWORD: # echo -n 'paswrd' | base64 <-> echo -n 'paswrd' | base64 --decode
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    envFrom:
    - secretRef:
        name: app-secret
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    env:
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: app-secret
            key: DB_PASSWORD
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
  # Inside Container : /opt/app-secret-volume
  volumes:
  - name: app-secret-volume
    secret:
     name: app-secret